### PR TITLE
fix: improve error message when the user wants to create a branch on a remote branch

### PR DESCRIPTION
**Pull request by Scra3**
### General

- [x] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [x] Test manually the implemented changes
- [x] Validate the code quality (indentation, syntax, style, simplicity, readability)

### Security

- [ ] Consider the security impact of the changes made

Link to CU-mk7zgx

### CODE REVIEW

**Comment by Scra3** [comment]
Capture d’écran 2021-12-06 à 15 17 36

**Comment by Scra3** [comment]
Success :
Capture d’écran 2021-12-06 à 15 18 00

**Comment by Scra3** [comment]
TO TEST THIS PR - you must have this code on your backend : https://github.com/ForestAdmin/forestadmin-server/pull/2889

**Review by guillaumedeslandes — APPROVED** [review]
Tested 👍

**Pull request merged**
