### PR TITLE
fix: handle properly mongo connection close

### PR DESCRIPTION
**Pull request by arnaud-moncel**
## Pull Request checklist:

- [X] Write an explicit title for the Pull Request, following [Conventional Commits specification](https://www.conventionalcommits.org)
- [ ] Create automatic tests
- [X] Test manually the implemented changes
- [ ] Review my own code (syntax, style, simplicity, readability)

### CODE REVIEW

**Comment by slimee** [comment]
this PR fixe the problem 💪

**Comment by slimee** [comment]
> this PR fixe the problem 💪
> 
> Have to check impacts maybe

There are no impacts outside commands `projects:create` and `schema:update`, these commands are working 👍

**Review by slimee — APPROVED** [review]
🚀

**Comment by arnaudbesnier** [comment]
Fix https://github.com/ForestAdmin/toolbelt/issues/208

**Pull request merged**
